# Personal Information
author: 
  name: Juan Facundo Quiñones
  birthday: 27/10/1990
  age: 34
  city: Pocito, San Juan, Argentina
  phone: +54 9 264-4558066
  email: quinonesjuanfacundo@gmail.com
  contact-form-id: https://formspree.io/f/<your-id> #Necessary to use form to send emails
  twitter: ""
  facebook: ""
  googleplus: ""
  instagram: ""
  github: https://www.github.com/jfquinones
  linkedin: https://www.linkedin.com/in/juan-facundo-quiñones 

year: "2023"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      language: "en"
  - scope:
      path: "es"
      type: "pages"
    values:
      layout: "default"
      languages: es
  - scope:
      path: "en"
      type: "pages"
    values:
      layout: "default"
      languages: en

languages:
  - code: "en"
    name: "English"
    path: "/en"
  - code: "es"
    name: "Español"
    path: "/es"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
